#!/usr/bin/env python3
"""Generate scripts/senator-quotes.mjs with sourced quotes for all 67 MN Senate districts."""
import json

entries = {}

def add(d, typ, text, ctx, date, theme, ntRef, ntKey, sources, humor="", future="", note=""):
    entries.setdefault(d, {"hypocrisy": [], "faith": []})
    q = {"text": text, "context": ctx, "date": date, "theme": theme, "ntRef": ntRef, "ntKey": ntKey, "sources": sources}
    if humor: q["humor"] = humor
    if future: q["inclusiveFuture"] = future
    if note: q["note"] = note
    entries[d][typ].append(q)

def h(d, *a, **k): add(d, "hypocrisy", *a, **k)
def f(d, *a, **k): add(d, "faith", *a, **k)

# ── 1–17 (partial batch from research) ──────────────────────────────────────
h(1, "There is a line in the sand. If you're accused with a felony, I think that's serious enough — our law has distinguished that as a very serious crime.", "Senate Minority Leader on caucus prostitution sting scandal", "2025-03", "Accountability", "Matthew 23:4", "M23_4", [{"label":"Star Tribune","url":"https://www.startribune.com/gop-state-sen-justin-eichorn-resigns-after-arrest-in-underage-prostitution-sting/601240150"},{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/sen-johnson-announces-senator-eichorn-has-submitted-a-letter-of-resignation/"}], humor="Strong words on felony charges — worth remembering when the caucus distributes commemorative Bibles instead of bread.", future="Real leadership means the same moral standard for everyone in the chamber.")

h(2, "We are offended the D.C. 'Squad', led by Minneapolis Congresswoman Ilhan Omar, is coming to Northern Minnesota to protest and further obstruct a thoroughly vetted, tested, and approved project.", "Joint statement on Line 3 pipeline protests", "2021", "Steward creation", "Matthew 5:9", "M5_9", [{"label":"Minnesota House","url":"https://www.house.mn.gov/members/profile/news/15395/46693"}], future="Energy policy that respects tribal sovereignty and creation is the Minnesota way forward.")

f(3, "Families are dealing with rising costs, communities are demanding real accountability on fraud, rural hospitals are facing serious threats from harmful federal decisions, and we still need to pass an infrastructure jobs bill that puts people to work.", "Statement opposing cuts to local government aid", "2026-03", "Healthcare & jobs", "Matthew 25:36", "M25_36", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-hauschild-calls-proposal-to-cut-local-government-aid-over-state-flag-nonsense/"}], future="Rural Minnesota thrives when hospitals stay open and neighbors have work.")

f(4, "This bill makes sure that the most vulnerable members of our community including seniors, children, and individuals with disabilities continue to have stable housing in their life.", "Vote advancing $9M supportive housing for northwest Minnesota", "2026-03", "Shelter neighbor", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-kupec-votes-to-advance-supporting-housing-funds-for-northwest-minnesota/"}], future="Stable housing for seniors and kids — that's prosperity with a roof.")

h(5, "Whether it was from those who serve our disability community or those that serve the elderly, they see that funding to those service providers are being reduced—all at the same time that we see these costs for illegal immigrants going through the roof... We need to put Minnesotans first.", "GOP press conference on MinnesotaCare enrollment", "2025-04", "Welcome stranger", "Matthew 25:35", "M25_35", [{"label":"Perham Focus","url":"https://www.perhamfocus.com/news/local/republican-lawmakers-in-mn-sound-alarm-on-surge-of-illegal-immigrants-enrolling-in-free-health-care-program"}], humor="Pitting grandparents against neighbors is divide-and-conquer, not charity.", future="We can fund elder care AND welcome immigrants.")

h(6, "Nearly half of Minnesota students are failing to meet reading and math standards. That should be a wake-up call for every leader in this state... Classrooms should be places where children learn how to read, write, and do math, not tools to use in political debates.", "Statement on MCA test scores", "2025", "Education", "Matthew 18:6", "M18_6", [{"label":"APG / hometownsource","url":"https://www.hometownsource.com/apgstate/heintzeman-statement-on-mca-scores-showing-half-of-students-failing-to-meet-math-and-reading/article_5ed82c1e-9337-5a02-b8b0-19d3b3b6d190.html"}], humor="Replaced Eichorn after a prostitution sting — education rhetoric hits different from that caucus.", future="Every child deserves support, not culture-war fodder.")

h(7, "This bill makes illegal immigrants and convicted criminals eligible for these funds, sending about one-third of the money to Hennepin county. The bill fails to put Minnesotans first.", "Opposition to $40M rental assistance bill", "2026", "Shelter stranger", "Matthew 25:35", "M25_35", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/senator-farnsworth-opposes-bailout-for-criminals-illegal-immigrants-and-metro/"}], future="Safe housing for every Minnesotan makes whole communities stronger.")

f(8, "I urge Minnesotans to challenge these narratives of scarcity. We can and should have the public goods we all deserve: universal healthcare, tuition-free education pre-K through higher ed, the ability to retire in comfort and security, affordable childcare, housing as a right, and a variety of thriving public goods and spaces, like libraries, parks and public transit, available to all.", "Statement on state budget forecast", "2025-03", "Prosperity for all", "Matthew 25:40", "M25_40", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-jen-mcewen-statement-on-state-budget-forecast/"}], future="Scarcity is a choice. Minnesota can choose abundance for everyone.")

h(9, "I think Minnesota families expect that we are going to put their budgets first and not use their hard-earned tax dollars to subsidize illegal immigration.", "CBS Minnesota interview on rolling back immigrant benefits", "2025", "Welcome stranger", "Matthew 25:35", "M25_35", [{"label":"CBS Minnesota","url":"https://www.cbsnews.com/minnesota/news/minnesota-undocumented-immigrant-proposed-roll-backs/"}], future="Minnesota families include immigrant families.")
h(9, "This is a program that unfortunately is incentivizing illegal immigrants to come here to Minnesota because of these benefits.", "WCCO Sunday Morning on MinnesotaCare", "2025-04-28", "Healthcare access", "Matthew 25:36", "M25_36", [{"label":"CBS Minnesota","url":"https://www.cbsnews.com/minnesota/news/minnesota-undocumented-immigrants-health-insurance-debate/"}], humor="Magnet theory meets Matthew 25 — the verse welcomes strangers.")

h(10, "Tim Walz belongs in prison, not office.", "Newsmax TV interview on state fraud", "2025-12-31", "Peacemakers", "Matthew 5:9", "M5_9", [{"label":"Newsmax","url":"https://rss.newsmax.com/newsmax-tv/nathan-wesenber-tim-walz-minnesota/2025/12/31/id/1240341/"}], humor="Blessed are the peacemakers — not those leading with 'belongs in prison.'", future="Disagree on policy; skip the prison cosplay.")
f(10, "People are hurting — they are struggling to pay their bills and get food on their tables.", "Guest column on affordability", "2025", "Feed the hungry", "Matthew 25:35", "M25_35", [{"label":"Brainerd Dispatch","url":"https://www.brainerddispatch.com/opinion/guest-opinion-a-bad-budget-and-missing-priorities"}], future="When Republicans name the pain, let's meet with bread, not Bibles.")

h(11, "They tried to tell people we're not coming after your hunting guns, (but) that piece of legislation is coming directly after your hunting guns.", "Post Bulletin interview on gun bills", "2025", "Peacemakers", "Matthew 5:9", "M5_9", [{"label":"Post Bulletin","url":"https://www.postbulletin.com/news/minnesota/minnesota-senator-explains-his-opposition-to-legislative-gun-control-bills"}])
f(11, "ICE MUST follow the Constitution. ICE must immediately stop this behavior. ICE must stop racial profiling and violating civil rights as has been experienced and documented by LAW ENFORCEMENT.", "Facebook post during Operation Metro Surge (MN Reformer)", "2026", "Dignity & justice", "Micah 6:8", "MIC6_8", [{"label":"Minnesota Reformer","url":"https://minnesotareformer.com/2026/03/26/republicans-experienced-a-very-different-operation-metro-surge/"}], humor="Plot twist: the Republican who remembered the Constitution.", future="This is the GOP voice Minnesota needs more of.")

h(12, "Start letting [wolves] be released in the backyards of these people that are in denial.", "Senate floor wolf management debate", "2024", "Peacemakers", "Matthew 5:9", "M5_9", [{"label":"Grand Forks Herald","url":"https://www.grandforksherald.com/news/minnesota/minnesota-senator-suggests-releasing-wolves-into-peoples-yards-who-do-not-want-a-wolf-hunt"}], future="Rural and urban Minnesotans can solve wildlife policy without revenge fantasies.")

f(13, "We should also remember to treat one another with the dignity, respect, and kindness that everyone deserves.", "Statement after Minneapolis ICE-involved shooting", "2026-01-08", "Dignity", "Matthew 22:39", "M22_39", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/howe-statement-on-yesterdays-ice-incident-in-minneapolis/"}], future="Kindness after violence — that's the Minnesota we can build.")
h(13, "How are we going to explain to our loved ones in these facilities... that they thought it was more important to preserve MNCare access for those here illegally?", "Condemning HHS budget with nursing-home cuts", "2025", "Healthcare triage", "Matthew 25:36", "M25_36", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/howe-condemns-human-services-budget-that-cuts-services-for-most-vulnerable-minnesotans-and-hits-district-13-with-crippling-nursing-home-cuts/"}], humor="False choice: elders vs. neighbors.", future="Fund nursing homes AND immigrant healthcare.")

f(14, "County workers are doing everything they can to connect residents with critical services, but these outdated IT systems make that job far harder than it needs to be.", "Stearns County demo on human services IT", "2026-03", "Feed the hungry", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-putnam-highlights-need-to-modernize-human-services-enrollment-it-systems-in-the-fight-against-fraud/"}], future="Modern systems get food and aid to families faster.")

h(15, "I strongly oppose any attempts to make Minnesota a sanctuary state from federal immigration laws.", "2024 session column opposing North STAR Act", "2024-02-17", "Welcome stranger", "Matthew 25:35", "M25_35", [{"label":"Marshall Independent","url":"https://www.marshallindependent.com/opinion/local-columns/2024/02/dedicate-this-session-to-correcting-bill-past-last-year/"}], future="Minnesota can be welcoming AND lawful — fear isn't policy.")

f(16, "Lang says we are all on the same side.", "KWKR interview defending peaceful protest rights", "2026-01", "Peacemaking", "Matthew 5:9", "M5_9", [{"label":"Willmar Radio","url":"https://www.willmarradio.com/news/senator-lang-defends-right-to-protest-but-interference-with-operations-can-be-tragic/article_22d8c29c-6396-4717-bdfe-bded20057cc7.html"}], note="Reporter paraphrase of on-air quote.", future="Minnesota needs more 'same side' energy.")
h(16, "I am in favor of construction of a wall and other necessary infrastructure on our border that gives complete control over entering and exiting the United States.", "iVoterGuide candidate questionnaire", "2022", "Welcome stranger", "Matthew 25:35", "M25_35", [{"label":"iVoterGuide","url":"https://ivoterguide.com/candidate/50494/race/12095/election/981"}], humor="Walls vs. 'same side' — pick a lane.")

h(17, "It's an unhealthy, sexual addiction.", "Floor speech opposing marriage equality", "2013-02-27", "Love neighbor", "Matthew 22:39", "M22_39", [{"label":"Star Tribune","url":"https://www.startribune.com/gruenhagen-homosexuality-is-a-sexual-addiction/193674061/"}], future="Minnesota families come in every shape. Dignity isn't optional.")
h(17, "Climate change is a complete United Nations fraud and lie.", "Energy committee testimony", "2021", "Steward creation", "Matthew 5:9", "M5_9", [{"label":"Session Daily","url":"https://www.house.leg.state.mn.us/sessiondaily/Story/17156"}])
h(17, "Women need to understand that abortion and pornography sends a certain message to men.", "Domestic violence discussion", "2023-03", "Protect vulnerable", "Matthew 23:27", "M23_27", [{"label":"Heartland Signal","url":"https://heartlandsignal.com/2023/03/29/minnesota-state-senator-blames-domestic-violence-on-women-abortion-and-pornography/"},{"label":"Star Tribune","url":"https://www.startribune.com/ethics-panel-takes-up-complaint-against-republican-senator-who-sent-graphic-video-link/600364366"}])

# ── 18–34 ───────────────────────────────────────────────────────────────────
f(18, "By equipping our care workers with the necessary resources, we affirm our commitment to the dignity and well-being of our aging loved ones.", "Nursing-home stabilization funding announcement", "2024-08", "Healthcare", "Matthew 25:36", "M25_36", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-nick-frentz-announces-a-total-of-1-03-million-will-go-out-in-august-to-four-nursing-homes-in-district-18/"}])

h(19, "They want to trust their government again. They want the fraud and mismanagement to stop. They want things to feel fair and well run.", "Statement on Gov. Walz not seeking reelection", "2026-01-05", "Governance", "Micah 6:8", "MIC6_8", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/statement-from-senator-john-jasinski-about-governor-walzs-decision-to-not-seek-reelection/"}])

h(20, "I have yet to meet a person in Minnesota that is hungry.", "Senate floor debate on free school meals", "2023-03-14", "Feed the hungry", "Matthew 25:35", "M25_35", [{"label":"CBS Minnesota","url":"https://www.cbsnews.com/minnesota/news/i-have-yet-to-meet-a-person-in-minnesota-that-is-hungry-outrage-follows-sen-drazkowskis-comments-on-free-school-meals/"},{"label":"NBC News","url":"https://www.nbcnews.com/politics/politics-news/state-gop-senator-says-never-met-hungry-minnesotan-rcna74969"}], humor="One in five kids in his district qualify for free lunch.", future="Every child deserves a full belly so they can learn.")
h(20, "Hunger is a relative term. I had a cereal bar for breakfast — I guess I'm hungry now.", "Same floor speech", "2023-03-14", "Feed the hungry", "Matthew 25:35", "M25_35", [{"label":"The Independent","url":"https://www.the-independent.com/news/world/americas/us-politics/minnesota-free-school-meals-republican-b2301038.html"}], humor="A cereal bar is not a school lunch program.")
h(20, "This is pure socialism.", "Opposing school meals bill", "2023-03-14", "Feed the hungry", "Matthew 25:35", "M25_35", [{"label":"NBC News","url":"https://www.nbcnews.com/politics/politics-news/state-gop-senator-says-never-met-hungry-minnesotan-rcna74969"}], humor="Jesus feeding five thousand was also pretty popular.")

h(21, "It was the most-disgusting end to a session in the 12 years I've been here.", "Reaction to 2024 omnibus end-of-session deal", "2024-05-20", "Legislative process", "Matthew 7:5", "M7_5", [{"label":"Twin Cities Business","url":"https://tcbmag.com/chaotic-close-to-minnesotas-2024-legislative-session/"}], humor="Called the omnibus a 'garbage bill' in the same remarks.")

f(22, "They want a transparent, realistic path to legal status for [people] who are hardworking, raising families, contributing to their communities, and filling critical jobs.", "Guest column on ICE enforcement", "2026-01", "Welcome stranger", "Matthew 25:35", "M25_35", [{"label":"Marshall Independent","url":"https://www.marshallindependent.com/opinion/local-columns/2026/01/whats-missing-from-ice-conversation-dialogue/"},{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/draheim-whats-missing-from-the-ice-conversation-dialogue/"}], future="Dialogue over shouting — Minnesota at its best.")
f(22, "If we want less shouting, fewer confrontations, and fewer lives lost, the answer isn't louder rhetoric. It's dialogue, and it's long overdue.", "Same ICE column", "2026-01", "Peacemaking", "Matthew 5:9", "M5_9", [{"label":"Marshall Independent","url":"https://www.marshallindependent.com/opinion/local-columns/2026/01/whats-missing-from-ice-conversation-dialogue/"}])

h(23, "Can you tell me what a typical work week looks like for you as a stewardess?", "Labor committee — addressed to Delta first officer", "2024-03", "Dignity at work", "Galatians 5:22", "GAL5_22", [{"label":"Star Tribune","url":"https://www.startribune.com/minnesota-senator-calls-delta-pilot-a-stewardess-at-legislative-hearing/600349338"},{"label":"CBS Minnesota","url":"https://www.cbsnews.com/minnesota/news/minnesota-senator-calls-delta-pilot-a-stewardess-during-senate-labor-committee/"}], humor="He apologized: 'I don't know why I said that.' Neither do we.", future="Every worker deserves respect at 30,000 feet or on the Senate floor.")

h(22, "We cannot justify spending hundreds of millions on individuals who broke the law to enter the country while we face cuts to special education, nursing homes, and disability services.", "Comment on MinnesotaCare repeal for undocumented adults", "2025-06", "Healthcare triage", "Matthew 25:36", "M25_36", [{"label":"Alpha News","url":"https://alphanews.org/legislature-passes-bill-repealing-minnesotacare-for-illegal-immigrant-adults/"}], note="Caucus floor position; same month Draheim published a contrasting dialogue column.", future="Fund schools AND neighbors — false choices help nobody.")

h(24, "Serving the people of Rochester and southeastern Minnesota has been a great privilege and responsibility.", "Retirement announcement", "2026", "Public service", "Micah 6:8", "MIC6_8", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/senator-carla-nelson-announces-retirement-from-minnesota-senate/"}], humor="Twenty years of constituent service vs. one year of commemorative Bibles.", future="Leadership rooted in listening beats performative faith.")
f(24, "After my father received an Alzheimer's diagnosis, I authored the Alzheimer's Research and Support Act, creating a competitive grant program for research and caregiver services.", "Retirement statement on legislative legacy", "2026", "Heal sick", "Matthew 25:36", "M25_36", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/senator-carla-nelson-announces-retirement-from-minnesota-senate/"}], future="Compassion policy from personal pain — that's scripture lived.")

f(25, "Minnesotans deserve to live with dignity and respect, no matter where they live.", "Manufactured Home Park Residents' Bill of Rights passage", "2025", "Housing dignity", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-liz-boldon-ushers-manufactured-home-park-residents-bill-of-rights-to-senate-passage/"}], future="Housing is a human right — not a Wall Street cash cow.")
f(25, "Housing is not meant to be a cash cow for Wall Street — it's meant to be a place for Minnesotans to come home at the end of the day, rest, cook, play, get together, raise a family, and build memories.", "Same bill statement", "2025", "Shelter neighbor", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-liz-boldon-ushers-manufactured-home-park-residents-bill-of-rights-to-senate-passage/"}])

# 26 Jeremy Miller R
f(26, "The bottom line is this: partisanship leads to polarization. Polarization leads to a dysfunctional government. And a dysfunctional government loses the trust of the people… Minnesotans want their elected officials working together and getting things done.", "Farewell speech on last day of 2026 session", "2026-05-18", "Peacemaking", "Matthew 5:9", "M5_9", [{"label":"Austin Daily Herald","url":"https://www.austindailyherald.com/opinion/partisanship-leads-to-polarization-a9038ea4"}], future="Bipartisanship isn't weakness — it's how Minnesota works.")
h(26, "There is a line in the sand.", "Caucus accountability after Eichorn prostitution charges", "2025-03", "Accountability", "Matthew 23:4", "M23_4", [{"label":"Star Tribune","url":"https://www.startribune.com/gop-state-sen-justin-eichorn-resigns-after-arrest-in-underage-prostitution-sting/601240150"}], note="Miller served as Senate President during expulsion debate.", humor="Leadership that draws lines — apply it to feeding kids too.", future="Same moral standard for every issue, not just scandals.")

h(27, "These are do-nothing executive orders that are meaningless and trying to distract from the Walz fraud scandals.", "Response to Gov. Walz gun-violence executive orders", "2025-12-16", "School safety", "Matthew 18:6", "M18_6", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/mathews-responds-to-governor-walzs-executive-orders-on-guns/"}], note="Same release proposed SRO funding for every school.")

h(28, "The agenda is so heinous, removing parental rights, the transgender ideology which puts our children in harm's way.", "Fox News interview on Walz/DFL record", "2024", "Love neighbor", "Matthew 22:39", "M22_39", [{"label":"Fox News","url":"https://www.foxnews.com/politics/minnesota-lawmaker-sounds-alarm-gov-walzs-radical-agenda-election-heinous"}], future="Trans Minnesotans are neighbors, not ideology.")

h(29, "Minnesotans do not support unmitigated infanticide.", "Judiciary committee on abortion amendment", "2026", "Compassion", "John 8:7", "J8_7", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/sen-holmstrom-fights-to-protect-life-and-title-ix/"}])
f(29, "All students deserve equal school safety aid, whether they attend public, private, or tribal schools.", "Amendment on equal private-school safety funding", "2025", "Protect children", "Matthew 18:6", "M18_6", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/senator-holmstrom-fights-for-equal-school-safety-funding-for-private-schools/"}], future="Every child deserves safety — full stop.")

h(30, "Their contributions are insulted every time we normalize those who broke the law.", "Column opposing driver's licenses for undocumented immigrants", "2023", "Welcome stranger", "Matthew 25:35", "M25_35", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/lucero-the-dangers-of-democrats-bill-to-give-illegal-immigrants-drivers-licenses/"}])

h(31, "If you're gonna party, you got to pay the consequences.", "Leaked caucus audio on abortion", "2024-03", "Compassion", "John 8:7", "J8_7", [{"label":"FOX 9","url":"https://www.fox9.com/news/dfl-responds-mn-gop-legislators-comment-why-he-opposes-abortion"}], humor="Christ stopped a public stoning. Different energy.")

h(32, "This new office is going to be a major tool to create a culture of accountability here in Minnesota. This independent agency will be the watchdog of taxpayers.", "Senate floor remarks before Office of Inspector General vote", "2026-05", "Accountability", "Micah 6:8", "MIC6_8", [{"label":"Sahan Journal","url":"https://sahanjournal.com/news/minnesota-legislature-fraud-office-of-inspector-general/"}], future="Accountability serves everyone — bipartisan when done right.")

h(33, "Elder abuse is something that cannot – and will not – be tolerated. The elderly are some of Minnesota's most vulnerable and to take advantage of that vulnerability is truly reprehensible.", "Response to Star Tribune senior-living abuse investigation", "2017", "Protect vulnerable", "Matthew 25:40", "M25_40", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/senator-housley-responds-star-tribune-report-detailing-abuse-neglect-minnesota-senior-living-facilities/"},{"label":"Star Tribune","url":"https://www.startribune.com/victims-denounce-a-failing-state-system-for-responding-to-reports-of-elder-abuse/474713293/"}], humor="Fierce advocate for elders — apply that same fire to hungry kids and immigrant neighbors.", future="Protect EVERY vulnerable Minnesotan consistently.")
f(33, "Any type of tax relief we can give these families will be a welcome break.", "Star Tribune on Toddler Tax Credit proposal", "2017", "Family affordability", "Matthew 25:40", "M25_40", [{"label":"Star Tribune","url":"https://www.startribune.com/gop-senator-proposes-toddler-tax-credit-for-minnesotans-with-young-children/294095371/"}], future="Tax relief for young families is good — so is healthcare for all families.")

f(34, "We cannot balance our budget at the expense of those who have no other safety net. We need sustainable long-term solutions that reflect our shared belief in dignity and opportunity for all Minnesotans.", "Statement on March 2025 budget forecast", "2025-03-06", "Healthcare", "Matthew 25:40", "M25_40", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-john-hoffman-statement-on-minnesota-budget-forecast/"}])

# ── 35–50 ───────────────────────────────────────────────────────────────────
f(35, "No man, woman or child is more or less in the eyes of our Lord... none of them are trash.", "Letter defending Somali Minnesotans", "2025-12", "Dignity", "Matthew 25:40", "M25_40", [{"label":"Star Tribune","url":"https://www.startribune.com/republican-state-sen-jim-abeler-trump-letter-somalis-invite-minnesota/601541054"}], humor="Plot twist: the Republican who remembered Matthew 25.", future="Neighbors defending neighbors — that's our Minnesota.")

f(36, "Being hungry makes learning almost impossible. Let's feed the kids.", "School meals bill — chief author", "2023-03", "Feed the hungry", "Matthew 25:35", "M25_35", [{"label":"CBS Minnesota","url":"https://www.cbsnews.com/minnesota/news/i-have-yet-to-meet-a-person-in-minnesota-that-is-hungry-outrage-follows-sen-drazkowskis-comments-on-free-school-meals/"}], humor="A teacher wrote the bill. A colleague said hunger doesn't exist.")

h(37, "Chickens are coming home to roost.", "Statement on state budget deficit", "2024", "Hypocrisy", "Matthew 7:5", "M7_5", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/senator-limmer-warns-chickens-coming-home-to-roost-due-to-looming-5-billion-deficit/"}], humor="The beam in thine own eye is also a bird.")

f(38, "It was very clear that Minnesota's Republicans are Hell-bent on removing our undocumented neighbors from MinnesotaCare.", "Statement on budget deal cutting immigrant healthcare", "2025-05", "Welcome stranger", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-susan-phas-statement-regarding-budget-negotiations-and-minnesotacare-for-undocumented-minnesotans/"}])

f(39, "Our neighbors deserve to live their lives in peace, free from this terror being inflicted on our community by our own federal government. Our students belong with their friends and classmates in school.", "Statement on Columbia Heights student released from ICE detention", "2025", "Welcome stranger", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-mary-kunesh-responds-to-release-of-columbia-heights-student-and-father-from-ice-detention-in-texas/"}], future="We welcome immigrants, feed our children, and take care of each other — that's Minnesota.")
f(39, "Without an explicit guarantee that these rights are protected and are held equally by all citizens, we legislators are not representing our constituents across Minnesota in the best way.", "Testimony on constitutional equality amendment", "2023-03-06", "Justice", "Micah 6:8", "MIC6_8", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-mary-kunesh-testifies-on-her-bill-to-amend-minnesota-constitution-to-ensure-equality-for-all/"}])

f(40, "Almost half (45%) of Minnesotans reported having to delay or forgo needed health care due to cost last year.", "Lead author statement on Minnesota Health Plan", "2025", "Heal sick", "Matthew 25:36", "M25_36", [{"label":"Senate DFL","url":"https://senatedfl.mn/dfl-legislators-call-for-bold-healthcare-reform-with-proposed-minnesota-health-plan/"}], future="Medical decisions belong to patients and doctors — not insurance companies.")
f(40, "Paying medical providers directly for the care they deliver to patients and eliminating the use of HMOs as a middleman will benefit patients, providers, and the state's bottom line.", "Statement on Patient-Centered Care legislation", "2026", "Healthcare", "Matthew 25:36", "M25_36", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-martys-legislation-to-kick-insurance-companies-out-of-minnesota-healthcare-programs-receives-hearing-governor-walz-issues-statement-supporting-the-proposal/"}])

f(41, "Minnesotans expect and deserve the water they use every day in their lives to be safe.", "Statement on PFAS standards and Hastings water upgrades", "2024-04-10", "Dignity", "Matthew 25:36", "M25_36", [{"label":"Senate DFL","url":"https://senatedfl.mn/new-pfas-standards-reveal-urgent-need-for-hastings-water-upgrades-says-senator-seeberger/"}])

f(42, "We cannot allow billionaires and dark money super PACs to bribe Minnesotans with money or prizes into voting or not voting a certain way.", "Bill presentation on election bribery prohibition", "2025-03-25", "Justice", "Micah 6:8", "MIC6_8", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-bonnie-westlin-presents-bill-to-prevent-bribery-in-minnesotas-electoral-system/"}], future="One person, one vote — democracy is sacred.")
f(42, "Everything we do in the Senate, everything we have in our society, is foundational on the right to vote. The democratic process is the cornerstone of what it means to be an American – one person, one vote.", "Elections policy bill passage", "2026-04-23", "Justice", "Micah 6:8", "MIC6_8", [{"label":"Senate DFL","url":"https://senatedfl.mn/senate-passes-elections-policy-bill/"}])

f(43, "Minnesotans are increasingly worried about the rising prices of gas, groceries and health care which federal actions and policies are accelerating and that target our state.", "Senate Taxes Committee advancing tax bill", "2026-03-05", "Healthcare", "Matthew 25:36", "M25_36", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-ann-rest-senate-taxes-committee-advances-tax-bill/"}])

f(44, "Undocumented residents who live, work, and raise families among us deserve the opportunity to use our roads legally and safely. I am proud to cast these votes to make Minnesota a more just, welcoming, and safer state.", "Senate passage of Restore the Vote and Driver's Licenses for All", "2023-02-22", "Welcome stranger", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/members-of-senate-poci-caucus-praise-historic-passage-of-restore-the-vote-and-drivers-licenses-for-all/"}])

f(45, "Thousands of people rely on these waters to drink, cook, bathe, and nourish the produce and crops that feed our communities.", "Statement on Boundary Waters mining protection", "2025-11-03", "Feed the hungry", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-ann-johnson-stewart-applauds-executive-order-protecting-the-boundary-waters/"}])

f(46, "Every Minnesotan, regardless of immigration status, has rights outlined in our Constitution that include the right against unreasonable search and seizure, the right to due process, and the right to seek counsel.", "Statement on constitutional rights of detainees", "2026-01-12", "Justice", "Micah 6:8", "MIC6_8", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-ron-latz-federal-authorities-must-honor-constitutional-rights-of-all-minnesotans-including-detainees/"}])

f(47, "Cryptocurrency scams have targeted some of our most vulnerable neighbors who have lost tens of thousands of dollars. In an instant, that money is gone with very little chance of recovery.", "Statement on crypto kiosk ban for elder fraud", "2026-04-27", "Protect vulnerable", "Matthew 25:40", "M25_40", [{"label":"Senate DFL","url":"https://senatedfl.mn/senate-passes-crypto-kiosk-ban/"}])

h(48, "The timing of the vote today feels performative at best.", "Floor speech on firearms omnibus bill", "2025-05", "Performative faith", "Matthew 6:5", "M6_5", [{"label":"The Catholic Spirit","url":"https://www.thecatholicspirit.com/news/local-news/senators-recall-annunciation-as-omnibus-firearms-bill-passes-focus-shifts-to-house/"}], humor="Performative is a strong word from the commemorative-KJV caucus.")

f(49, "These are the policies our students, educators, and communities need to ensure every Minnesotan child receives a world-class education in a safe, welcoming environment.", "Education policy omnibus bill", "2023-03-09", "Dignity", "Matthew 18:6", "M18_6", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-steve-cwodzinski-successfully-passes-education-policy-omnibus-bill-to-uplift-students-support-teachers-and-revitalize-schools-to-senate-floor/"}])

f(50, "Take insulin away from diabetics, inhalers from people with asthma, cancer treatment from people who just want a few more years with their children — all for political points.", "Press conference on healthcare access", "2025-06", "Heal sick", "Matthew 25:36", "M25_36", [{"label":"FOX 9","url":"https://www.fox9.com/news/dfl-progressive-caucus-disrupts-walz-budget-conference-over-undocumented-migrant-insurance/"}])

# ── 51–67 ───────────────────────────────────────────────────────────────────
f(51, "Today's roundtable discussion was alarming, as we heard from Minnesotans about the threats the government shutdown poses to programs that help families stay in their homes and healthy.", "Roundtable on federal shutdown impacts on SNAP and housing", "2025-10-30", "Feed the hungry", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-wiklund-response-to-government-shutdown-roundtable-in-richfield/"}])

f(52, "Ranked choice voting strengthens democracy, promotes local control, and allows voters to have a stronger voice in our elections.", "Senate Elections Committee hearing", "2025-03-06", "Justice", "Micah 6:8", "MIC6_8", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-jim-carlsons-ranked-choice-voting-bill-heard-in-senate-elections-committee/"}])

f(53, "We are a strong enough and a good enough state to ensure all of us have access to health care. And we can no longer allow a person's background or income to determine if they can receive treatment – we are better than that.", "Commentary on MinnesotaCare expansion", "2018-10-23", "Healthcare", "Matthew 25:36", "M25_36", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-klein-expanding-minnesotacare-would-increase-choice-and-competition/"}])

h(54, "In no world should registering a car be more expensive than a car payment, yet that is a common reality for many.", "Press release on tab-fee affordability", "2026-04", "Affordability", "Matthew 23:4", "M23_4", [{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/living-in-minnesota-is-taxing-pratt-joins-senate-republicans-in-discussing-tax-increases-that-have-made-life-unaffordable/"}], future="Affordability matters — so does healthcare for neighbors.")

f(55, "Healthcare is a human right, and it is infuriating to hear from and about Minnesotans making painful choices between seeking basic care and paying their other bills.", "Statement after healthcare roundtable in Northfield", "2025-10", "Healthcare", "Matthew 25:36", "M25_36", [{"label":"Senate DFL","url":"https://senatedfl.mn/senate-select-committee-holds-insurance-and-healthcare-roundtable-in-northfield/"}], future="No one should choose between rent and insulin.")
f(55, "In the face of rising rents and mortgages across the state, we are taking decisive action to keep Minnesotans safely housed.", "Bipartisan housing legislation passage", "2025-05", "Housing", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-lindsey-port-celebrates-passage-of-bipartisan-housing-legislation/"}])

f(56, "Gruenhagen violated Senate norms — sending a graphic surgery video to all senators.", "Ethics complaint author", "2024", "Justice", "Micah 6:8", "MIC6_8", [{"label":"Star Tribune","url":"https://www.startribune.com/ethics-panel-takes-up-complaint-against-republican-senator-who-sent-graphic-video-link/600364366"}])

h(57, "I think we need to be very thoughtful about how we're spending taxpayer dollars.", "Floor debate on school meals — sought delay before voting YES", "2023-03", "Feed the hungry", "Matthew 25:35", "M25_35", [{"label":"CBS Minnesota","url":"https://www.cbsnews.com/minnesota/news/i-have-yet-to-meet-a-person-in-minnesota-that-is-hungry-outrage-follows-sen-drazkowskis-comments-on-free-school-meals/"}], note="Duckworth ultimately voted for free school meals after seeking broader package.", humor="Thoughtful delay on feeding kids — then voted yes. More of that.")
f(57, "We do potentially have a need that we need to address.", "Same school meals vote", "2023-03", "Feed the hungry", "Matthew 25:35", "M25_35", [{"label":"CBS Minnesota","url":"https://www.cbsnews.com/minnesota/news/i-have-yet-to-meet-a-person-in-minnesota-that-is-hungry-outrage-follows-sen-drazkowskis-comments-on-free-school-meals/"}], humor="He voted to feed the kids while colleagues said hunger was imaginary.", future="When Republicans cross the aisle for kids, Minnesota gets better.")

h(58, "We don't have a revenue problem. We have a spending problem.", "Guest column on state deficit", "2025-04-11", "Fiscal policy", "Matthew 7:5", "M7_5", [{"label":"Southern Minn","url":"https://www.southernminn.com/lonsdale_area_news_review/opinion/sen-lieske-we-don-t-have-a-revenue-problem-we-have-a-spending-problem/article_f18e7cb1-67e4-4c10-9bc0-370f0800fc08.html"},{"label":"MN Senate Republicans","url":"https://www.mnsenaterepublicans.com/lieske-we-dont-have-a-revenue-problem-we-have-a-spending-problem/"}], humor="Signature catchphrase — repeated across 2025–2026 columns.")

f(59, "These are our friends and neighbors who contribute to economic and cultural well-being of our state.", "Statement condemning targeting of Somali community", "2025-12-04", "Welcome stranger", "Matthew 25:40", "M25_40", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-bobby-joe-champion-strongly-denounces-trumps-continued-targeting-of-minnesotas-somali-community/"}])

f(60, "I will be focused on education, housing, housing, housing and lowering the cost of health care.", "Interview after winning SD 60 special election", "2025-01-28", "Housing & healthcare", "Matthew 25:36", "M25_36", [{"label":"Star Tribune","url":"https://www.startribune.com/doron-clark-minnesota-senate-dfl-republican-democrat-district-60-kari-dziedzic/601213222"}])

f(61, "When every person has access to healthcare, housing, treatment, prevention, and the basic security of a safe, stable life, new infections fall and lives are saved.", "World AIDS Day statement", "2025-12-01", "Healthcare", "Matthew 25:36", "M25_36", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-scott-dibble-statement-on-honoring-world-aids-day/"}])

f(62, "Thank you for speaking out when others stay silent.", "Thanking Sen. Abeler for defending Somali neighbors", "2025-12", "Good Samaritan", "Luke 10:33", "L10_33", [{"label":"Star Tribune","url":"https://www.startribune.com/trump-racist-rant-somali-community-minnesota/601542035"}])

f(63, "When our community is suffering, the entire state is suffering, too.", "Minnesota Asian Pacific Caucus statement", "2025-03", "Solidarity", "Matthew 25:40", "M25_40", [{"label":"Senate DFL","url":"https://senatedfl.mn/senate-minnesota-asian-pacific-caucus-statement-on-aapi-legislative-hearing/"}])

f(64, "They are our neighbors.", "Healthcare for undocumented Minnesotans — POCI Caucus", "2025-06", "Welcome stranger", "Matthew 25:35", "M25_35", [{"label":"FOX 9","url":"https://www.fox9.com/news/dfl-progressive-caucus-disrupts-walz-budget-conference-over-undocumented-migrant-insurance/"}])

f(65, "Governor Walz has been a steadfast ally in the Capital Investment Committee's work to maintain state assets and provide Minnesotans with clean water and dignified housing.", "Statement on 2026 bonding proposal", "2026-01-16", "Housing", "Matthew 25:35", "M25_35", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-pappas-statement-on-governor-walz-2026-bonding-proposal/"}])

f(66, "We have heard from Minnesotans who failed the written driver's license exam because it uses unnecessarily confusing and complex language.", "Plain language driver's license exam bill", "2024-04", "Dignity", "Matthew 22:39", "M22_39", [{"label":"Senate DFL","url":"https://senatedfl.mn/senator-clare-oumou-verbeten-ushers-bill-to-implement-plain-language-standards-on-written-drivers-license-exam-to-bipartisan-passage-in-senate/"}], future="Accessibility is dignity — especially for immigrant neighbors learning to drive.")
f(66, "In this role, I will continue to fight to make Minnesota a more inclusive and equitable place for all.", "Statement on election as Assistant Majority Leader", "2024-03", "Justice", "Micah 6:8", "MIC6_8", [{"label":"LinkedIn (Sen. Oumou Verbeten)","url":"https://www.linkedin.com/posts/clareoumouverbeten_i-am-grateful-to-my-colleagues-for-electing-activity-7171852781161558016-PVFs"}])

f(67, "Every Minnesotan deserves to have their rights protected and to be able to live with dignity.", "Senate passage of Restore the Vote and Driver's Licenses for All", "2023-02-22", "Dignity", "Matthew 25:40", "M25_40", [{"label":"Senate DFL","url":"https://senatedfl.mn/members-of-senate-poci-caucus-praise-historic-passage-of-restore-the-vote-and-drivers-licenses-for-all/"}])

# Validate all 67 districts have quotes
missing = [d for d in range(1, 68) if d not in entries]
if missing:
    raise SystemExit(f"Missing districts: {missing}")

R_DISTRICTS = {1,2,5,6,7,9,10,11,12,13,15,16,17,19,20,21,22,23,24,26,27,28,29,30,31,32,33,37,48,54,57,58}
for d in range(1, 68):
    e = entries[d]
    if d in R_DISTRICTS and not e["hypocrisy"] and not e["faith"]:
        raise SystemExit(f"R district {d} has no quotes")
    if d not in R_DISTRICTS and not e["faith"]:
        raise SystemExit(f"D district {d} missing faith quotes")

# Output as JS module
lines = ['// AUTO-GENERATED by scripts/generate-all-quotes.py — do not edit by hand', 'export const RAW_QUOTES = ' + json.dumps(entries, indent=2) + ';']
with open('/agent/christ-not-in-vain/scripts/senator-quotes-data.json', 'w') as out:
    json.dump(entries, out, indent=2)
print('Wrote senator-quotes-data.json with', len(entries), 'districts')